---
- name: Run test suite
  hosts: all
  tasks:
    - name: Perform tests
      ansible.builtin.script:
        cmd: tests.sh
        chdir: '{{ install_path }}/isaac-project0'
      register: test_result

    - name: Test info
      ansible.builtin.debug:
        var: test_result.stdout_lines

