---
# This task uninstalls isaac-project0

- name: Uninstall
  hosts: all
  become: yes
  tasks:
    - name: Remove project folder
      ansible.builtin.script:
        cmd: uninstall.sh
        chdir: '{{ install_path }}'
        removes: '{{ install_path }}/isaac-project0/p0.py'
